server:
  port: 8888
spring:
  cloud:
    config:
      discovery:
        enabled: true
      server:
        encrypt.enabled: true
        git:
          uri: https://github.com/doruk581/config-repository/
          searchPaths: creditapproveservice,identityservice